apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    labels:
        name: order-service
    name: order-service
    namespace: shyamsanju
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: order-service
        spec:
            containers:
                -
                    name: order-service
                    image: 'order-service:1.0'
