apiVersion: v1
kind: Service
metadata:
    name: order-service
    namespace: shyamsanju
spec:
    type: NodePort
    ports:
        -
            port: 9300
            targetPort: 9300
            nodePort: 30300
    selector:
        app: order-service
