apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    labels:
        name: shipping-service
    name: shipping-service
    namespace: shyamsanju
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: shipping-service
        spec:
            containers:
                -
                    name: shipping-service
                    imagePullPolicy: Never
                    image: 'shipping-service:1.0'
