apiVersion: v1
kind: Service
metadata:
    name: shipping-service
    namespace: shyamsanju
spec:
    type: NodePort
    ports:
        -
            port: 9300
            targetPort: 9300
            nodePort: 30400
    selector:
        app: shipping-service
