apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    labels:
        name: inventory-service
    name: inventory-service
    namespace: shyamsanju
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: inventory-service
        spec:
            containers:
                -
                    name: inventory-service
                    imagePullPolicy: "IfNotPresent"
                    image: 'shyamsanju/inventory-service:1.0'
